version = 1
SPDX-PackageName = "spotoptim"
SPDX-PackageSupplier = "bartzbeielstein <32470350+bartzbeielstein@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/sequential-parameter-optimization/spotoptim"

[[annotations]]
path = [".flake8", ".gitignore", ".python-version", ".releaserc.json", "mkdocs.yml", "pyproject.toml", "uv.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".github/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["docs/**", "README.md", "CHANGELOG.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["examples/**", "notebooks/**", "local/**", "site/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "scripts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "tests/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"
