version = 1
SPDX-PackageName = "spotoptim"
SPDX-PackageSupplier = "bartzbeielstein <32470350+bartzbeielstein@users.noreply.github.com>"
SPDX-PackageDownloadLocation = "https://github.com/sequential-parameter-optimization/spotoptim"

[[annotations]]
path = [
    ".flake8",
    ".gitignore",
    ".python-version",
    ".releaserc.json",
    "mkdocs.yml",
    "pyproject.toml",
    "uv.lock",
    "spotoptim.code-workspace"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".github/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["docs/**", "README.md", "CHANGELOG.md", "MODEL_CARD.md", "CONTRIBUTING.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
    "**/*.md",
    "**/*.html",
    "**/*.css",
    "**/*.js",
    "**/*.woff",
    "**/*.csv",
    "**/*.sh",
    "**/*.bat",
    "**/*.qmd",
    "**/*.ipynb",
    "**/*.png",
    "**/*.jpg",
    "**/*.svg",
    "**/*.toml",
    "**/*.txt",
    "**/*.yml",
    "**/*.yaml",
    "**/*.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 bartzbeielstein"
SPDX-License-Identifier = "AGPL-3.0-or-later"
